### ISSUE TITLE
Publishing to NodeBB from Wordpress only works for default post types

### ISSUE THREAD

**Issue by jshaffstall** [revir/nodebb-plugin-blog-comments2#1]
Line 157 of wordpress.js uses the Wordpress API to get the contents of a post:

`adminXHR.open('GET', wordpressURL + '?json=get_post&post_id=' + articleID);`

That only works for posts of the default 'post' type.  Posts of different types return that the post could not be found.  

It'd be nice if publishing could work with any post type, not just the default.

**Comment by revir** [comment]
Thank you so much.
